tasks:

  build-deps:

    steps:

    - checkout

    - commands:

    - run: pip3 install pytest

    - run: pip3 freeze --local > requirements.txt

    - run: pip3 install pytest-cov

    - run: pytest --cov app/

    - run: pytest --cov app/ --cov-report=html:test-coverage.html

    - codecov/codecov-action@v3

    - run: 
    -$ProgressPreference = 'SilentlyContinue'
     Invoke-WebRequest -Uri https://uploader.codecov.io/latest/windows/codecov.exe 
    -Outfile codecov.exe.\codecov.exe -t ${CODECOV_TOKEN} --url https://<your-codecov-self-hosted-url>

